name: debug concurrency

concurrency:
  group: debug
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: context
        uses: jameskyburz/github-script@main
        with:
          script: |
            console.log('context', JSON.stringify(context, null, 2))
      - name: sleep
        uses: jameskyburz/github-script@main
        with:
          script: |
            console.log('sleeping')
            await new Promise(x => setTimeout(x, 15000))
            console.log('awake')


