name: show secret

on:
  workflow_dispatch:
    inputs:
      secret-name:
        description: "secret to show"
        required: true

jobs:
  show:
    runs-on: ubuntu-latest
    env:
      SECRET_NAME: ${{ github.event.inputs.secret-name }}
    steps:
      - run: |
          if [[ -n '${{ secrets.SECRET_PASSWORD }}' ]]; then
            echo ${{ secrets[env.SECRET_NAME] }} | \
              openssl aes-256-cbc \
                -k '${{ secrets.SECRET_PASSWORD }}' \
                -e \
                -pbkdf2 \
                -a
          fi
